"""Optional local-LLM narrative polish via Ollama (grounded, graceful).

Augments the deterministic insight/profile narratives with fluent prose
generated by a locally-hosted model (no data leaves the deployment). The model
is *strictly grounded*: it receives only the facts the deterministic engines
already derived and is instructed to rephrase those facts as a neutral
investigative summary — never to infer identity, add identifiers, or draw
conclusions. When Ollama is disabled, unreachable, or the model is missing, the
helpers return ``None`` (failing fast on a short connect timeout) and callers
fall back to their deterministic narrative, so this never blocks or degrades the
pipeline. The generated prose is an analyst aid and remains human-editable.
"""
from __future__ import annotations

import json
import logging
import os
import time
from typing import Optional

logger = logging.getLogger(__name__)

OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://ollama:11434").rstrip("/")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.2:3b")
LLM_NARRATIVES_ENABLED = os.getenv("LLM_NARRATIVES_ENABLED", "1").strip().lower() not in (
    "0", "false", "no", "off", "",
)

# Fail fast when Ollama is not running; allow generation itself to take longer.
_CONNECT_TIMEOUT = 3.0
_READ_TIMEOUT = float(os.getenv("OLLAMA_TIMEOUT", "60"))
_MAX_FACTS_CHARS = 6000
_MAX_TOKENS = 360

# Negative cache: after a failed reach, skip network attempts for this many
# seconds so a missing/stopped Ollama costs one slow probe, not one per call.
_FAILURE_COOLDOWN = 60.0
_last_failure_ts = 0.0


def _in_cooldown() -> bool:
    return (time.monotonic() - _last_failure_ts) < _FAILURE_COOLDOWN


def _mark_failure() -> None:
    global _last_failure_ts
    _last_failure_ts = time.monotonic()


def _mark_success() -> None:
    global _last_failure_ts
    _last_failure_ts = 0.0

_SYSTEM_PROMPT = (
    "You are an analyst assistant supporting a lawful, court-authorised OSINT "
    "investigation conducted by an Indian law-enforcement agency. You receive "
    "STRUCTURED FACTS already derived by a deterministic engine from open-source "
    "evidence. Write a concise, neutral intelligence summary using ONLY those "
    "facts. Strict rules: (1) never invent names, locations, identifiers, "
    "numbers, employers or affiliations not present in the facts; (2) never "
    "speculate about guilt, criminality, or real-world identity; (3) frame every "
    "observation as an investigative lead requiring independent verification; "
    "(4) plain professional prose, at most two short paragraphs, no markdown "
    "headings, no preamble such as 'Here is'. If the facts are sparse, say so "
    "briefly rather than embellishing."
)


class LLMNarrator:
    """Thin, best-effort client for grounded narrative generation via Ollama."""

    def available(self) -> bool:
        """True only when narratives are enabled and Ollama answers quickly."""
        if not LLM_NARRATIVES_ENABLED or _in_cooldown():
            return False
        try:
            import httpx

            with httpx.Client(timeout=_CONNECT_TIMEOUT) as client:
                resp = client.get(f"{OLLAMA_BASE_URL}/api/tags")
            if resp.status_code == 200:
                _mark_success()
                return True
            _mark_failure()
            return False
        except Exception:  # noqa: BLE001 — availability probe is best-effort
            _mark_failure()
            return False

    def generate(self, facts: dict, instruction: str = "") -> Optional[str]:
        """Return grounded prose for ``facts`` (or None on any failure/disable)."""
        if not LLM_NARRATIVES_ENABLED or _in_cooldown():
            return None
        try:
            import httpx

            payload_facts = json.dumps(facts, default=str, ensure_ascii=False)[:_MAX_FACTS_CHARS]
            prompt = (
                (instruction.strip() + "\n\n" if instruction else "")
                + "STRUCTURED FACTS (JSON):\n"
                + payload_facts
            )
            body = {
                "model": OLLAMA_MODEL,
                "system": _SYSTEM_PROMPT,
                "prompt": prompt,
                "stream": False,
                "options": {"temperature": 0.2, "top_p": 0.9, "num_predict": _MAX_TOKENS},
            }
            timeout = httpx.Timeout(_READ_TIMEOUT, connect=_CONNECT_TIMEOUT)
            with httpx.Client(timeout=timeout) as client:
                resp = client.post(f"{OLLAMA_BASE_URL}/api/generate", json=body)
            if resp.status_code != 200:
                logger.debug("ollama generate non-200: %s %s", resp.status_code, resp.text[:200])
                _mark_failure()
                return None
            text = (resp.json().get("response") or "").strip()
            _mark_success()
            return text or None
        except Exception as exc:  # noqa: BLE001 — narrative is optional enrichment
            logger.debug("ollama narrative unavailable: %s", exc)
            _mark_failure()
            return None
